/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lcweb.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-27-2009
 * 
 * XDoclet definition:
 * @struts.form name="commonsForm"
 */
public class CommonsForm extends ActionForm {
}