/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lcweb.struts.form;

import org.apache.struts.action.ActionForm;

 
public class LoginForm extends ActionForm {
	 
 

}