/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lcweb.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.lcweb.bean.pojo.NewsContentManage;

/** 
 * MyEclipse Struts
 * Creation date: 11-03-2009
 * 
 * XDoclet definition:
 * @struts.form name="newsClientActionForm"
 */
public class NewsClientActionForm extends ActionForm {
	/*
	 * Generated Methods
	 */
NewsContentManage newsContentMange=new NewsContentManage();
	public NewsContentManage getNewsContentMange() {
	return newsContentMange;
}

public void setNewsContentMange(NewsContentManage newsContentMange) {
	this.newsContentMange = newsContentMange;
}
private String path;
	public String getPath() {
	return path;
}

public void setPath(String path) {
	this.path = path;
}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}