/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lcweb.struts.form;

import java.util.List;

import org.apache.struts.action.ActionForm;

import com.lcweb.base.util.PageList;
import com.lcweb.bean.pojo.BasicDepartment;
import com.lcweb.bean.pojo.BasicPerson;
import com.lcweb.bean.pojo.BasicUnit;
import com.lcweb.bean.pojo.SysRole;
import com.lcweb.bean.pojo.SysRolePerson;

 
public class RightManageForm extends ActionForm {
	
	private PageList pageList;
    private SysRole sysRole  = new SysRole();
    private List roleList;
    private String roleId;
    private List moduleList;  
    private SysRolePerson sysRolePerson = new SysRolePerson();
    private BasicDepartment basicDepartment =new BasicDepartment();
    private BasicPerson basicPerson = new BasicPerson(); 
    private String DepartmentName;
    private BasicUnit basicUnit = new BasicUnit();
    private List deptList; 
    private List usertList;  
    private String style;
    private List personList;
    
    
    
    public String getDepartmentName() {
		return DepartmentName;
	}
	public void setDepartmentName(String departmentName) {
		DepartmentName = departmentName;
	}
	public BasicUnit getBasicUnit() {
		return basicUnit;
	}
	public void setBasicUnit(BasicUnit basicUnit) {
		this.basicUnit = basicUnit;
	}
	public List getUsertList() {
		return usertList;
	}
    public void setUsertList(List usertList) {
		this.usertList = usertList;
	}

	public List getDeptList() {
		return deptList;
	}

	public void setDeptList(List deptList) {
		this.deptList = deptList;
	}

	public BasicPerson getBasicPerson() {
		return basicPerson;
	}

	public void setBasicPerson(BasicPerson basicPerson) {
		this.basicPerson = basicPerson;
	}

	public SysRolePerson getSysRolePerson() {
		return sysRolePerson;
	}

	public void setSysRolePerson(SysRolePerson sysRolePerson) {
		this.sysRolePerson = sysRolePerson;
	}

	public List getRoleList() {
		return roleList;
	}

	public void setRoleList(List roleList) {
		this.roleList = roleList;
	}

	public List getModuleList() {
		return moduleList;
	}

	public void setModuleList(List moduleList) {
		this.moduleList = moduleList;
	}

	public SysRole getSysRole() {
		return sysRole;
	}

	public void setSysRole(SysRole sysRole) {
		this.sysRole = sysRole;
	}

	public PageList getPageList() {
		return pageList;
	}

	public void setPageList(PageList pageList) {
		this.pageList = pageList;
	}
	public BasicDepartment getBasicDepartment() {
		return basicDepartment;
	}
	public void setBasicDepartment(BasicDepartment basicDepartment) {
		this.basicDepartment = basicDepartment;
	}
	public String getStyle() {
		return style;
	}
	public void setStyle(String style) {
		this.style = style;
	}
	public String getRoleId() {
		return roleId;
	}
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}
	public List getPersonList() {
		return personList;
	}
	public void setPersonList(List personList) {
		this.personList = personList;
	}	
	
}