<%@taglib uri="http://struts.apache.org/tags-html"  prefix="html"%>
<%@taglib uri="http://struts.apache.org/tags-bean"  prefix="bean"%>
<%@taglib uri="http://struts.apache.org/tags-logic"  prefix="logic"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%> 
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<script language="javascript" type="text/javascript" src="${pageContext.request.contextPath }/js/jquery.js"></script>
<script language="javascript" type="text/javascript" src="${pageContext.request.contextPath }/js/checkright.js"></script>
<script language="javascript" type="text/javascript" src="${pageContext.request.contextPath }/js/common.js"></script>
<script language="javascript" type="text/javascript" src="${pageContext.request.contextPath }/js/coolwindow.js"></script>

