package com.agilefly.bean;

import com.agilefly.utils.ApplicationConfig;



/**
 * SysConfig generated by MyEclipse Persistence Tools
 */

public class SysConfig  implements java.io.Serializable {


    // Fields    

     private String sysConfigCode;
     private String sinaWeibo;
     private String onlineQq;
     private String picQq;


    // Constructors

	/** default constructor */
    public SysConfig() {
    }

    
    /** full constructor */
    public SysConfig(String sinaWeibo, String onlineQq) {
        this.sinaWeibo = sinaWeibo;
        this.onlineQq = onlineQq;
    }

   
    // Property accessors

    public String getSysConfigCode() {
        return this.sysConfigCode;
    }
    
    public void setSysConfigCode(String sysConfigCode) {
        this.sysConfigCode = sysConfigCode;
    }

    public String getSinaWeibo() {
        return this.sinaWeibo;
    }
    
    public void setSinaWeibo(String sinaWeibo) {
        this.sinaWeibo = sinaWeibo;
    }

    public String getOnlineQq() {
        return this.onlineQq;
    }
    
    public void setOnlineQq(String onlineQq) {
        this.onlineQq = onlineQq;
    }
    
    public String getPicQq() {
		return picQq;
	}


	public void setPicQq(String picQq) {
		this.picQq = picQq;
	}
	public static void main(String[] args) {
		System.out.println(ApplicationConfig.get("index.onlineqq"));
	}
}